package com.soothe.sapApplication.ui.issueForProductionOrder.Model

import com.google.gson.annotations.SerializedName
import java.io.Serializable

data class ProductionListModel(
    @SerializedName("odata.metadata") var odataMetadata: String,
    @SerializedName("odata.nextLink") var odataNextLink: String,
    var value: ArrayList<Value>,
    ):Serializable  {
    data class Value(
        var AbsoluteEntry: String,
        var DocumentNumber: String,
        var Series: String,
        var ItemNo: String,
        var ProductionOrderStatus: String,
        var ProductionOrderType: String,
        var PlannedQuantity: Double,
        var CompletedQuantity: Double,
        var RejectedQuantity: Double,
        var PostingDate: String,
        var DueDate: String,
        var ProductionOrderOriginEntry: Long? = null,
        var ProductionOrderOriginNumber: Long? = null,
        var ProductionOrderOrigin: String,
        var UserSignature: Long,
        var Remarks: Any? = null,
        var ClosingDate: String? = null,
        var ReleaseDate: String? = null,
        var CustomerCode: Any? = null,
        var Warehouse: String,
        var InventoryUOM: String? = null,
        var JournalRemarks: String,
        var TransactionNumber: Long? = null,
        var CreationDate: String,
        var Printed: String,
        var DistributionRule: String,
        var Project: String? = null,
        var DistributionRule2: String,
        var DistributionRule3: String,
        var DistributionRule4: String,
        var DistributionRule5: String,
        var UoMEntry: Long,
        var StartDate: String,
        var ProductDescription: String? = null,
        var Priority: Long,
        var RoutingDateCalculation: String,
        var UpdateAllocation: String,
        var SAPPassport: Any? = null,
        var AttachmentEntry: Any? = null,
        var U_PM: Double? = null,
        var U_Width: Double? = null,
        var U_GSM: Double? = null,
        var U_FLEX: Double? = null,
        var U_TBQ: Double? = null,
        var U_Length: Double? = null,
        var U_Cal: Any? = null,
        var U_QRCode: Any? = null,
        var U_QRPath: Any? = null,
        var ProductionOrderLines: ArrayList<ProductionOrderLine>,
        var ProductionOrdersSalesOrderLines: List<Any?>,
        var ProductionOrdersStages: List<Any?>,
        var ProductionOrdersDocumentReferences: List<Any?>
    ) : Serializable

    data class ProductionOrderLine(
        var isScanned : Boolean = false,
        var DocumentAbsoluteEntry: Long,
        var LineNumber: String ,
        var ItemNo: String? = null,
        var BaseQuantity: Double,
        var PlannedQuantity: Double,
        var IssuedQuantity: Double,
        var ProductionOrderIssueType: String,
        var Warehouse: String,
        var VisualOrder: Long,
        var DistributionRule: Any? = null,
        var LocationCode: Long? = null,
        var Project: Any? = null,
        var DistributionRule2: Any? = null,
        var DistributionRule3: Any? = null,
        var DistributionRule4: Any? = null,
        var DistributionRule5: Any? = null,
        var UoMEntry: Long,
        var UoMCode: Long,
        var WipAccount: Any? = null,
        var ItemType: String,
        var LineText: Any? = null,
        var AdditionalQuantity: Double,
        var ResourceAllocation: Any? = null,
        var StartDate: String? = null,
        var EndDate: String? = null,
        var StageID: Any? = null,
        var RequiredDays: Double,
        var ItemName: String? = null,
        var SerialNumbers: List<Any?>,
        var BatchNumbers: List<Any?>
    ): Serializable

}