package com.soothe.sapApplication.ui.deliveryOrderModule.Model

import com.google.gson.annotations.SerializedName
import java.io.Serializable

data class DeliveryModel(
    @SerializedName("odata.metadata") val metadata: String,
    val value: ArrayList<Value> = ArrayList()
) {
    data class Value (
        @SerializedName("odata.etag") val odataEtag: String,
        val DocEntry: Long,
        val DocNum: String,
        val DocObjectCode: String,
        val DocType: String,
        val HandWritten: String,
        val Printed: String,
        val DocDate: String,
        val DocDueDate: String,
        val CardCode: String,
        val CardName: String,
        val Address: String,
        val NumAtCard: Any? = null,
        val DocTotal: Double,
        val AttachmentEntry: Any? = null,
        val BPL_IDAssignedToInvoice: String,
        val DocCurrency: String,
        val DocRate: Double,
        val Reference1: String,
        val Reference2: Any? = null,
        val Comments: Any? = null,
        val JournalMemo: String,
        val PaymentGroupCode: Long,
        val DocTime: String,
        val SalesPersonCode: Long,
        val TransportationCode: Long,
        val Confirmed: String,
        val ContactPersonCode: Long,
        val UpdateDate: String,
        val FinancialPeriod: Long,
        val UserSign: Long,
        val TransNum: Any? = null,
        val U_PrntTrfr: Any? = null,
        val U_PrntDcNm: Any? = null,
        val U_DcType: Any? = null,
        val U_PrntSrs: Any? = null,
        val U_InvTrfr: Any? = null,
        val U_InvDcNm: Any? = null,
        val U_CIN_GENo: Any? = null,
        val U_CIN_GPNo: Any? = null,
        val U_CIN_VHNo: Any? = null,
        val U_CIN_TRNm: Any? = null,
        val U_CIN_InvNo: Any? = null,
        val U_CIN_GPENo: Any? = null,
        val U_CIN_GPDNo: Any? = null,
        val U_CIN_GEDNo: Any? = null,
        val U_CIN_GateD: Any? = null,
        val U_QRImg: Any? = null,
        val U_PRL: Double,
        val U_CRL: Double,
        val U_IMFRL: Double,
        val U_RL: Double,
        val Document_ApprovalRequests: List<Any?>,
        val DocumentLines: List<DocumentLine> = ArrayList(),
        val ElectronicProtocols: List<Any?>,
        val DocumentAdditionalExpenses: List<Any?>,
        val WithholdingTaxDataWTXCollection: List<Any?>,
        val WithholdingTaxDataCollection: List<Any?>,
        val DocumentSpecialLines: List<Any?>,
        val TaxExtension: TaxExtension,
        val AddressExtension: AddressExtension,
        val DocumentReferences: List<Any?>
    ):Serializable

    data class DocumentLine (
        var isScanned : Int=0 ,
        var totalPktQty : Int=0 ,
        var NavisionCode : String?=null ,
        val LineNum: Int,
        val BarCode: Any? = null,
        val U_BOX_QTY: String,
        val BaseType: String,
        val BaseEntry: String,
        val U_IQTY: String,
        val ItemCode: String,
        val ItemDescription: String,
        val Quantity: Double,
        val ShipDate: String,
        val Price: Double,
        val PriceAfterVAT: Double,
        val Currency: String,
        val Rate: Double,
        val DiscountPercent: Double,
        val UnitPrice: Double,
        val VendorNum: String,
        val SerialNum: Any? = null,
        val WarehouseCode: String,
        val BaseOpenQuantity: Double,
        val SalesPersonCode: Int,
        val CommisionPercent: Double,
        val TreeType: String,
        val AccountCode: String,
        val UseBaseUnits: String,
        val SupplierCatNum: String,
        val CostingCode: Any? = null,
        val ProjectCode: String,
        val Height1: Double,
        val Hight1Unit: Any? = null,
        val Height2: Double,
        val Height2Unit: Any? = null,
        val Lengh1: Double,
        val Lengh1Unit: Any? = null,
        val Lengh2: Double,
        val Lengh2Unit: Any? = null,
        val Weight1: Double,
        val Weight1Unit: Any? = null,
        val Weight2: Double,
        val Weight2Unit: Any? = null,
        val Factor1: Double,
        val Factor2: Double,
        val Factor3: Double,
        val Factor4: Double,
        val Address: String,
        val TaxCode: String,
        val TaxType: String,
        val TaxLiable: String,
        val PickStatus: String,
        val PickQuantity: Double,
        val U_GSMSO: Double,
        val U_GSM: Double,
        val PickListIdNumber: Any? = null,
        val OriginalItem: Any? = null,
        val NetTaxAmount: Double,
        val NetTaxAmountFC: Double,
        val NetTaxAmountSC: Double,
        val UnitsOfMeasurment: Double,
        val LineTotal: Double,
        val TaxPercentagePerRow: Double,
        val TaxTotal: Double,
        val LineStatus: String,
        val PackageQuantity: Double,
        val LineType: String,
        val RemainingOpenQuantity: Double,
        val OpenAmount: Double,
        val OpenAmountFC: Double,
        val OpenAmountSC: Double,
        val ActualBaseEntry: Any? = null,
        val ActualBaseLine: Any? = null,
        val DocEntry: Long,
        val GrossProfit: Double,
        val GrossProfitFC: Double,
        val GrossProfitSC: Double,
        val PriceSource: String,
        val UoMEntry: Long,
        val UoMCode: String,
        val InventoryQuantity: Double,
        val RemainingOpenInventoryQuantity: Double,
        val ItemType: String,
        val ChangeInventoryQuantityIndependently: String,
        val GrossPrice: Double,
        val GrossTotal: Double,
        val GrossTotalFC: Double,
        val GrossTotalSC: Double,
        val ReverseCharge: String,
        val ShipToCode: String,
        val ShipToDescription: String,
        val OwnerCode: Any? = null,
        val LineTaxJurisdictions: List<LineTaxJurisdiction>,
        val DocumentLineAdditionalExpenses: List<Any?>,
        val WithholdingTaxLines: List<Any?>,
        val SerialNumbers: List<Any?>,
        val BatchNumbers: List<Any?>,
        val DocumentLinesBinAllocations: List<Any?>
    ):Serializable

    data class LineTaxJurisdiction (
        val JurisdictionCode: String,
        val JurisdictionType: Long,
        val TaxAmount: Double,
        val TaxAmountSC: Double,
        val TaxAmountFC: Double,
        val TaxRate: Double,
        val DocEntry: Int,
        val LineNumber: Int,
        val RowSequence: Int,
        val ExternalCalcTaxRate: Double,
        val ExternalCalcTaxAmount: Double,
        val ExternalCalcTaxAmountFC: Double,
        val ExternalCalcTaxAmountSC: Double
    ):Serializable

    data class TaxExtension (
        val TaxId0: String,
        val TaxId1: Any? = null,
        val TaxId2: Any? = null,
        val TaxId3: Any? = null,
        val TaxId4: Any? = null,
        val TaxId5: Any? = null,
        val TaxId6: Any? = null,
        val TaxId7: Any? = null,
        val TaxId8: Any? = null,
        val TaxId9: Any? = null,
        val State: String,
        val County: Any? = null,
        val Incoterms: Any? = null,
        val Vehicle: Any? = null,
        val VehicleState: Any? = null,
        val NFRef: Any? = null,
        val Carrier: Any? = null,
        val PackQuantity: Any? = null,
        val PackDescription: Any? = null,
        val Brand: Any? = null,
        val ShipUnitNo: Any? = null,
        val NetWeight: Double,
        val GrossWeight: Double,
        val StreetS: String,
        val BlockS: Any? = null,
        val BuildingS: String,
        val CityS: String,
        val ZipCodeS: Any? = null,
        val CountyS: Any? = null,
        val StateS: String,
        val CountryS: String,
        val StreetB: String,
        val BlockB: Any? = null,
        val BuildingB: String,
        val CityB: String,
        val ZipCodeB: Any? = null,
        val CountyB: Any? = null,
        val StateB: String,
        val CountryB: String,
        val ImportOrExport: String,
        val MainUsage: Any? = null,
        val GlobalLocationNumberS: Any? = null,
        val GlobalLocationNumberB: Any? = null,
        val TaxId12: String,
        val TaxId13: Any? = null,
        val BillOfEntryNo: Any? = null,
        val BillOfEntryDate: Any? = null,
        val OriginalBillOfEntryNo: Any? = null,
        val OriginalBillOfEntryDate: Any? = null,
        val ImportOrExportType: String,
        val PortCode: Any? = null,
        val DocEntry: Long,
        val BoEValue: Any? = null,
        val ClaimRefund: String,
        val DifferentialOfTaxRate: Long,
        val IsIGSTAccount: Any? = null
    ) :Serializable

    data class AddressExtension (
        val ShipToStreet: String,
        val ShipToStreetNo: Any? = null,
        val ShipToBlock: Any? = null,
        val ShipToBuilding: String,
        val ShipToCity: String,
        val ShipToZipCode: Any? = null,
        val ShipToCounty: Any? = null,
        val ShipToState: String,
        val ShipToCountry: String,
        val ShipToAddressType: Any? = null,
        val BillToStreet: String,
        val BillToStreetNo: Any? = null,
        val BillToBlock: Any? = null,
        val BillToBuilding: String,
        val BillToCity: String,
        val BillToZipCode: Any? = null,
        val BillToCounty: Any? = null,
        val BillToState: String,
        val BillToCountry: String,
        val BillToAddressType: Any? = null,
        val ShipToGlobalLocationNumber: Any? = null,
        val BillToGlobalLocationNumber: Any? = null,
        val ShipToAddress2: Any? = null,
        val ShipToAddress3: Any? = null,
        val BillToAddress2: Any? = null,
        val BillToAddress3: Any? = null,
        val PlaceOfSupply: String,
        val PurchasePlaceOfSupply: String,
        val DocEntry: Long,
        val GoodsIssuePlaceBP: Any? = null,
        val GoodsIssuePlaceCNPJ: Any? = null,
        val GoodsIssuePlaceCPF: Any? = null,
        val GoodsIssuePlaceStreet: Any? = null,
        val GoodsIssuePlaceStreetNo: Any? = null,
        val GoodsIssuePlaceBuilding: Any? = null,
        val GoodsIssuePlaceZip: Any? = null,
        val GoodsIssuePlaceBlock: Any? = null,
        val GoodsIssuePlaceCity: Any? = null,
        val GoodsIssuePlaceCounty: Any? = null,
        val GoodsIssuePlaceState: Any? = null,
        val GoodsIssuePlaceCountry: Any? = null,
        val GoodsIssuePlacePhone: Any? = null,
        val GoodsIssuePlaceEMail: Any? = null,
        val GoodsIssuePlaceDepartureDate: Any? = null,
        val DeliveryPlaceBP: Any? = null,
        val DeliveryPlaceCNPJ: Any? = null,
        val DeliveryPlaceCPF: Any? = null,
        val DeliveryPlaceStreet: Any? = null,
        val DeliveryPlaceStreetNo: Any? = null,
        val DeliveryPlaceBuilding: Any? = null,
        val DeliveryPlaceZip: Any? = null,
        val DeliveryPlaceBlock: Any? = null,
        val DeliveryPlaceCity: Any? = null,
        val DeliveryPlaceCounty: Any? = null,
        val DeliveryPlaceState: Any? = null,
        val DeliveryPlaceCountry: Any? = null,
        val DeliveryPlacePhone: Any? = null,
        val DeliveryPlaceEMail: Any? = null,
        val DeliveryPlaceDepartureDate: Any? = null
    ) :Serializable


}
